- app/models/relationship.rb
- app/models/user.rb
- db/schema.rb
user model and relationship ready for for following/follower feature!
still gotta figure out controller and user interface.
> implemented followers and following in user model

- app/controllers/events_controller.rb
- app/models/event.rb
- app/models/user.rb
- app/views/events/index.html.erb
- app/views/events/show.html.erb
- config/initializers/geocoder.rb
- config/routes.rb
sudo code to see what to do next
finished simple_form for creating event: user can choose title, description, + end time
end time if not provided set to default 24hrs
still missing the destroy an event 
still missing update event (end_time = Time.now bttn)
> Event module controller

- app/controllers/events_controller.rb
- app/views/events/index.html.erb
- config/routes.rb
- db/schema.rb
I added a terminate option which will send the end date of a event to time.now, and a if statement that won't show events that are expired. also added the delete function
> added terminate and destroy

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/_forms.scss
- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/config/_bootstrap_variables.scss
- app/assets/stylesheets/config/_colors.scss
- app/assets/stylesheets/config/_fonts.scss
- app/controllers/application_controller.rb
- app/views/devise/registrations/new.html.erb
- app/views/devise/sessions/new.html.erb
- app/views/devise/shared/_links.html.erb
- app/views/layouts/application.html.erb
- app/views/shared/_navbar.html.erb
- config/initializers/simple_form_bootstrap.rb
- db/schema.rb
Created the register, login, remove Navbar from all pages and change it a little bit.
> Css Login, register and navbar

- app/controllers/users_controller.rb
- app/models/user.rb
- app/views/users/index.html.erb
Just need to add a link to the user search
> There is now a user search with its own index

- Gemfile
- Gemfile.lock
- app/controllers/application_controller.rb
- app/controllers/comments_controller.rb
- app/controllers/events_controller.rb
- app/controllers/users_controller.rb
- app/models/user.rb
- app/policies/application_policy.rb
- app/policies/comment_policy.rb
- app/policies/event_policy.rb
- app/policies/user_policy.rb
- app/views/comments/index.html.erb
- app/views/devise/registrations/edit.html.erb
- app/views/events/index.html.erb
- app/views/events/show.html.erb
- db/migrate/20190328185319_add_admin_to_users.rb
- db/schema.rb
- db/seeds.rb
- test/policies/comments_policy_test.rb
- test/policies/event_policy_test.rb
- test/policies/user_policy_test.rb
check out commits
pundit gem install
migration admin user
policy install for user, comments and events
> Admin user config

- app/assets/stylesheets/components/_avatar.scss
- app/assets/stylesheets/components/_forms.scss
- app/assets/stylesheets/components/_navbar.scss
- app/views/events/index.html.erb
- app/views/layouts/application.html.erb
- app/views/shared/_flashes.html.erb
- app/views/shared/_navbar.html.erb
Change all the navbar to final model
> Navbar change 

- app/controllers/events_controller.rb
- app/javascript/packs/application.js
- app/javascript/plugins/init_mapbox.js
- app/policies/event_policy.rb
> current location working

- app/controllers/application_controller.rb
- app/controllers/users_controller.rb
- app/models/comment.rb
- app/models/event.rb
- app/models/relationship.rb
- app/models/user.rb
- app/views/comments/index.html.erb
- app/views/devise/confirmations/new.html.erb
- app/views/events/index.html.erb
- app/views/users/show.html.erb
- config/initializers/devise.rb
made some validations for username
cleaneup  the code a bit
> cleanned code a bit

- app/assets/stylesheets/components/_avatar.scss
- app/assets/stylesheets/components/_buttons.scss
- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/_userShow.scss
- app/javascript/packs/application.js
- app/javascript/packs/count_down_time.js
- app/javascript/packs/user_show_map.js
- app/javascript/plugins/create.js
- app/javascript/plugins/init_mapbox.js
- app/views/events/index.html.erb
- app/views/users/show.html.erb
created the user show, made a second map just for it.
> User profile

- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/event-popup.scss
- app/javascript/packs/application.js
- app/javascript/packs/event_popup.js
- app/javascript/plugins/init_mapbox.js
- app/views/events/_event-popup.html.erb
- app/views/events/index.html.erb
came up with a work around to stick html into mapbox popups. Only downside is that it is very rendering intensive
> made popups work, kinda

- app/assets/stylesheets/components/_index.scss
> smaaalll fix

- app/assets/stylesheets/components/_navbar.scss
> april's fool

- app/assets/stylesheets/components/_buttons.scss
- app/assets/stylesheets/components/_userShow.scss
- app/javascript/plugins/userAutocomplete.js
- app/views/devise/registrations/edit.html.erb
- app/views/shared/_navbar.html.erb
- app/views/users/show.html.erb
> Back button

- app/controllers/events_controller.rb
- app/javascript/packs/user_show_map.js
- app/models/event.rb
- app/models/user.rb
- app/policies/event_policy.rb
- app/views/users/show.html.erb
- config/initializers/devise.rb
now facebook log in is working
> bugs fix for facebook log in

- app/assets/stylesheets/components/_edit-form.scss
- app/assets/stylesheets/components/_navbar.scss
- app/assets/stylesheets/components/event-popup.scss
- app/views/devise/registrations/edit.html.erb
- app/views/shared/_navbar.html.erb
Change the css for the Search users
> Search user find css

- app/assets/stylesheets/components/_avatar.scss.erb
- app/assets/stylesheets/components/_buttons.scss
- app/assets/stylesheets/components/_comments.scss
- app/assets/stylesheets/components/event-popup.scss
- app/views/events/_event-popup.html.erb
Small fixes css for pop up. font-sizes and align some items
> Small fixes for event Popup

- app/assets/stylesheets/components/_buttons.scss
- app/assets/stylesheets/components/_form-login.scss
- app/assets/stylesheets/components/_user-show.scss
- app/views/devise/sessions/new.html.erb
- app/views/devise/shared/_links.html.erb
- app/views/users/show.html.erb
btn for facebook looking good
you can only see end now btn and trash btn from user#show if u are current_user
> facebook btn, delet and end event btn fix

- app/assets/stylesheets/components/_mapbox.scss
- app/assets/stylesheets/components/_navbar.scss
> fixed navbar sticky

- app/assets/stylesheets/components/_form-login.scss
- app/assets/stylesheets/components/event-popup.scss
- app/javascript/packs/count_down_time.js
- app/views/shared/_navbar.html.erb
- app/views/users/show.html.erb
Fixed small user show problems, change the eye in active and ended time.
> Fixed small problems
